export const RESUME ="https://drive.google.com/file/d/1LHn9YQleYC9aZCh6RDOZkpC8kS_0cBbx/view?usp=sharing"
export const INTERNSHIP="https://drive.google.com/file/d/1F3n6AWGlYlsXAGyxCHwAck2jTZpHyaj5/view?usp=sharing"
export const GRADUATION_MARKSHEET="https://drive.google.com/file/d/1wSxNMxKpEw991vVvRgWinns70QA1gGEn/view?usp=sharing"
export const TWELTH_MARKSHEET="https://drive.google.com/file/d/1JOjQTfRR2ZT-P83p-GsVv6IB-UO17mVD/view?usp=sharing"
export const TENTH_MARKSHEET="https://drive.google.com/file/d/1UzgvyDCNqJTXdKFeLoNzws-DCtgVDCPv/view?usp=sharing"
export const GITHUB ="https://github.com/karina108"
export const LINKEDIN = "https://www.linkedin.com/in/singhkarina/"                          
export const EMAIL = "mailto:singhkarina90@gmail.com"
export const PHONE = "tel:7973742809"
export const FACEBOOK="https://www.facebook.com/profile.php?id=100057250654607"
export const TWITTER="https://x.com/singhkarina90/"                                     
export const INSTAGRAM="https://www.instagram.com/karinakarina4575/"
//PROJECTS
export const SikshalayProjectLink ="https://github.com/Karina108/Sikshalay"
export const TemperatureProjectLink= "https://github.com/Karina108/Temperature-Converter"
export const portfolioProjectLink="https://github.com/Karina108/Portfolio"